import {
	TBloodDonation,
	TClothesItem,
	TFoodItem,
	TMedicalCase,
	TMedicalSupply,
	TStationaryItem,
	TTeachingPost,
	TToyItem,
	User,
	Organization,
	Donor,
	TSchoolSuppliesItem,
} from '../types';

{
	/* Toys list Images*/
}
import BoardGames from '../assets/Images/Donor/Lists/Toys/board-games.jpg';
import Dolls from '../assets/Images/Donor/Lists/Toys/dolls.jpeg';
import Cars from '../assets/Images/Donor/Lists/Toys/cars.jpeg';
import Outdoor from '../assets/Images/Donor/Lists/Toys/outdoor.jpeg';
import Sports from '../assets/Images/Donor/Lists/Toys/sports.jpeg';

{
	/* Clothes list Images*/
}
import Jackets from '../assets/Images/Donor/Lists/Clothes/jackets.jpeg';
import Pants from '../assets/Images/Donor/Lists/Clothes/pants.jpeg';
import Shirts from '../assets/Images/Donor/Lists/Clothes/tshirts.jpeg';

{
	/* Food list Images*/
}
import Canned from '../assets/Images/Donor/Lists/Food/canned.jpeg';
import Fresh from '../assets/Images/Donor/Lists/Food/fresh.jpeg';
import Frozen from '../assets/Images/Donor/Lists/Food/frozen.jpeg';

{
	/* Medical Supplies list Images*/
}
import Masks from '../assets/Images/Donor/Lists/MedicalSupplies/masks.jpeg';
import Gloves from '../assets/Images/Donor/Lists/MedicalSupplies/gloves.jpeg';
import Sanitizer from '../assets/Images/Donor/Lists/MedicalSupplies/sanitizer.jpeg';

{
	/* School Supplies list Images*/
}
import Pencils from '../assets/Images/Donor/Lists/School/pencils.jpeg';
import Notebooks from '../assets/Images/Donor/Lists/School/Notebooks.jpeg';
import Backpacks from '../assets/Images/Donor/Lists/School/backpacks.jpeg';
import books from '../assets/Images/Donor/Lists/School/books.jpeg';

{
	/* Teaching Posts list Images*/
}
import teachingPost from '../assets/Images/Donor/Lists/TeachingPosts/teachingpost.jpeg';

{
	/* Blood list Images*/
}

export const credentials: User[] = [
	{
		type: 'admin',
		username: 'admin',
		password: 'admin123',
	},
	{
		type: 'donor',
		username: 'donor',
		password: 'donor123',
		donorType: 'regular',
	},
	{
		type: 'donor',
		username: 'teacher',
		password: 'teacher123',
		donorType: 'teacher',
	},
	{
		type: 'donor',
		username: 'doctor',
		password: 'doctor123',
		donorType: 'doctor',
	},
	{
		type: 'organisation',
		username: 'org',
		password: 'org123',
	},
];

export const organizations: Organization[] = [
	{
		id: 1,
		name: 'Hope Shelter',
		type: 'Non-profit',

		street: '123 Main St',
		area: 'Anytown',
		gov: 'CA',
		zip: '12345',

		contactEmail: 'hope@shelter.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},

	{
		id: 2,
		name: 'Salvation Army',
		type: 'Non-profit',

		street: '789 Oak St',
		area: 'Othertown',
		gov: 'NY',
		zip: '12345',

		contactEmail: 'sal@gmail.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 3,
		name: 'Goodwill',
		type: 'Non-profit',

		street: '456 Elm St',
		area: 'Another Town',
		gov: 'TX',
		zip: '12345',

		contactEmail: 'GOOd@gmail.com',
		status: 'pending',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 4,
		name: 'Red Cross',
		type: 'Non-profit',

		street: '101 Pine St',
		area: 'Anytown',
		gov: 'CA',
		zip: '12345',

		contactEmail: 'red@gmail.com',
		status: 'pending',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 5,
		name: 'Dope Shelter',
		type: 'Non-profit',

		street: '123 unrad St',
		area: 'Anytown',
		gov: 'TX',
		zip: '12345',

		contactEmail: 'dope@shelter.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 6,
		name: 'X shelter',
		type: 'Profit',

		street: '789 rad St',
		area: 'Anytown',
		gov: 'NY',
		zip: '12345',

		contactEmail: 'x@gmail.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 7,
		name: 'Future Shelter',
		type: 'Profit',

		street: '789 Rad St',
		area: 'Othertown',
		gov: 'CA',
		zip: '12345',

		contactEmail: 'fut@gmail.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},
	{
		id: 8,
		name: 'World Shelter',
		type: 'Non-profit',

		street: '144 Sun St',
		area: 'Another Town',
		gov: 'TX',
		zip: '12345',

		contactEmail: 'wa@gmail.com',
		status: 'approved',

		img: 'https://via.placeholder.com/150',
	},
];

export const donor: Donor[] = [
	{
		firstname: 'Amr',
		secondname: 'Hossam',
		address: '123 Elm St, Anytown, CA 12345',
		email: 'amr@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Nada',
		secondname: 'Saleh',
		address: '143 Pine St, Anytown, CA 12345',
		email: 'nada@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Salma',
		secondname: 'Ahmed',
		address: '154 Sec St, Wheretown, CA 12345',
		email: 'salama@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Dalia',
		secondname: 'Habib',
		address: '167 Cosec St, Howtown, CA 12345',
		email: 'dalia@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Tia',
		secondname: 'Abdelrahman',
		address: '148 Pint St, Whytown, CA 12345',
		email: 'tia@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Hala',
		secondname: 'Ashraf',
		address: '196 Live St, Whentown, CA 12345',
		email: 'hala@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Noor',
		secondname: 'Ismail',
		address: '134 Hello St, Thentown, CA 12345',
		email: 'noor@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Jannah',
		secondname: 'Omar',
		address: '189 Bye St, Theirtown, CA 12345',
		email: 'jannah@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Ahmed',
		secondname: 'Mostafa',
		address: '33 Why St, Nevertown, CA 12345',
		email: 'ahmed@gmail.com',
		status: 'pending',
	},
	{
		firstname: 'Ali',
		secondname: 'Basha',
		address: '69 Okay St, Yestown, CA 12345',
		email: 'ali@gmail.com',
		status: 'pending',
	},
];
export const foods: TFoodItem[] = [
	{
		id: 1,
		name: 'Canned Food',
		type: 'canned',
		quantity: 50,
		img: Canned,
	},
	{
		id: 2,
		name: 'Apple',
		type: 'fruits and vegetables',
		quantity: 30,
		img: Fresh,
	},
	{
		id: 3,
		name: 'Baked Food',
		type: 'baked',
		quantity: 20,
		img: Frozen,
	},
	{
		id: 4,
		name: 'Canned Food',
		type: 'canned',
		quantity: 50,
		img: Canned,
	},
	{
		id: 5,
		name: 'Fresh Produce',
		type: 'fresh',
		quantity: 30,
		img: Fresh,
	},
	{
		id: 6,
		name: 'Baked Food',
		type: 'baked',
		quantity: 20,
		img: Frozen,
	},
	{
		id: 7,
		name: 'Canned Food',
		type: 'canned',
		quantity: 50,
		img: Canned,
	},
	{
		id: 8,
		name: 'Fresh Produce',
		type: 'fresh',
		quantity: 30,
		img: Fresh,
	},
	{
		id: 9,
		name: 'Banana',
		type: 'fruits and vegetables',
		quantity: 20,
		img: Frozen,
	},
	{
		id: 10,
		name: 'Canned Food',
		type: 'canned',
		quantity: 50,
		img: Canned,
	},
	{
		id: 11,
		name: 'Fresh Produce',
		type: 'fresh',
		quantity: 30,
		img: Fresh,
	},
	{
		id: 12,
		name: 'Baked Food',
		type: 'baked',
		quantity: 20,
		img: Frozen,
	},
];

export const medicalSupplies: TMedicalSupply[] = [
	{
		id: 1,
		name: 'Masks',
		type: 'equipment',
		quantity: 100,
		img: Masks,
		use: 'General',
	},
	{
		id: 2,
		name: 'Gloves',
		type: 'equipment',
		quantity: 50,
		img: Gloves,
		use: 'General',
	},
	{
		id: 3,
		name: 'Sanitizer',
		type: 'equipment',
		quantity: 30,
		img: Sanitizer,
		use: 'General',
	},
	{
		id: 4,
		name: 'Masks',
		type: 'equipment',
		quantity: 100,
		img: Masks,
		use: 'General',
	},
	{
		id: 5,
		name: 'X-Ray Machine',
		type: 'device',
		quantity: 10,
		img: '',
		use: 'General',
	},
	{
		id: 6,
		name: 'Stethoscope',
		type: 'device',
		quantity: 20,
		img: '',
		use: 'General',
	},
	{
		id: 7,
		name: 'Thermometer',
		type: 'device',
		quantity: 30,
		img: '',
		use: 'General',
	},
	{
		id: 8,
		name: 'Panadol',
		type: 'medicine',
		quantity: 40,
		img: '',
		use: 'Pain',
	},
	{
		id: 9,
		name: 'Comtrex',
		type: 'medicine',
		quantity: 50,
		img: '',
		use: 'Flu',
	},
	{
		id: 10,
		name: 'Strepsils',
		type: 'medicine',
		quantity: 60,
		img: '',
		use: 'Cold',
	},
	{
		id: 11,
		name: 'Dettol',
		type: 'medicine',
		quantity: 70,
		img: '',
		use: 'Other',
	},
];
export const schoolSupplies: TSchoolSuppliesItem[] = [
	{
		id: 1,
		name: 'Pencils',
		type: 'General',
		quantity: 100,
		img: Pencils,
		itemType: 'stationary',
	},
	{
		id: 2,
		name: 'Notebooks',
		type: 'General',
		quantity: 50,
		img: Notebooks,
		itemType: 'stationary',
	},
	{
		id: 3,
		name: 'Backpacks',
		type: 'General',
		quantity: 30,
		img: Backpacks,
		itemType: 'stationary',
	},
	{
		id: 4,
		name: 'Pencils',
		type: 'General',
		quantity: 100,
		img: Pencils,
		itemType: 'stationary',
	},
	{
		id: 5,
		name: 'Notebooks',
		type: 'General',
		quantity: 50,
		img: Notebooks,
		itemType: 'stationary',
	},
	{
		id: 6,
		name: 'Backpacks',
		type: 'General',
		quantity: 30,
		img: Backpacks,
		itemType: 'stationary',
	},
	{
		id: 7,
		name: 'My little Pony',
		quantity: 100,
		img: Pencils,
		itemType: 'book',
		author: 'Author 1',
		bookName: 'My little Pony',
		language: 'English',
		edition: '1st',
		summary: 'Summary 1',
	},
	{
		id: 8,
		name: 'Book 1',
		img: books,
		quantity: 10,
		bookName: 'Book 1',
		author: 'Author 1',
		language: 'English',
		edition: '1st',
		summary: 'Summary 1',
		itemType: 'book',
	},
	{
		id: 9,
		name: 'Book 2',
		img: books,
		quantity: 20,
		bookName: 'Book 2',
		author: 'Author 2',
		language: 'English',
		edition: '2nd',
		summary: 'Summary 2',
		itemType: 'book',
	},
	{
		id: 10,
		name: 'Book 3',
		img: books,
		quantity: 30,
		bookName: 'Book 3',
		author: 'Author 3',
		language: 'English',
		edition: '3rd',
		summary: 'Summary 3',
		itemType: 'book',
	},
	{
		id: 11,
		name: 'Book 4',
		img: books,
		quantity: 40,
		bookName: 'Book 4',
		author: 'Author 4',
		language: 'English',
		edition: '4th',
		summary: 'Summary 4',
		itemType: 'book',
	},
	{
		id: 12,
		name: 'Book 5',
		img: books,
		quantity: 50,
		bookName: 'Book 5',
		author: 'Author 5',
		language: 'English',
		edition: '5th',
		summary: 'Summary 5',
		itemType: 'book',
	},
	{
		id: 13,
		name: 'Book 6',
		img: books,
		quantity: 60,
		bookName: 'Book 6',
		author: 'Author 6',
		language: 'English',
		edition: '6th',
		summary: 'Summary 6',
		itemType: 'book',
	},
];

export const bloodCases: TBloodDonation[] = [
	{
		id: 1,
		name: 'item 1',
		volume: 3,
		img: 'image1.jpg',
		bloodType: 'O+',
		hospital: 'Hospital 1',
		area: 'Area 1',
		gov: 'Gov 1',
		address: 'Address 1',
	},
	{
		id: 2,
		name: 'item 2',
		bloodType: 'A+',
		volume: 1,
		img: 'image2.jpg',
		hospital: 'Hospital 2',
		area: 'Area 2',
		gov: 'Gov 2',
		address: 'Address 2',
	},
	{
		id: 3,
		name: 'item 3',
		bloodType: 'B+',
		volume: 2,
		img: 'image3.jpg',
		hospital: 'Hospital 3',
		area: 'Area 3',
		gov: 'Gov 3',
		address: 'Address 3',
	},
	{
		id: 4,
		name: 'item 4',
		bloodType: 'AB+',
		volume: 4,
		img: 'image4.jpg',
		hospital: 'Hospital 4',
		area: 'Area 4',
		gov: 'Gov 4',
		address: 'Address 4',
	},
	{
		id: 5,
		name: 'item 5',
		bloodType: 'O-',
		volume: 5,
		img: 'image5.jpg',
		hospital: 'Hospital 5',
		area: 'Area 5',
		gov: 'Gov 5',
		address: 'Address 5',
	},
	{
		id: 6,
		name: 'item 6',
		bloodType: 'A-',
		volume: 6,
		img: 'image6.jpg',
		hospital: 'Hospital 6',
		area: 'Area 6',
		gov: 'Gov 6',
		address: 'Address 6',
	},
	{
		id: 7,
		name: 'item 7',
		bloodType: 'B-',
		volume: 7,
		img: 'image7.jpg',
		hospital: 'Hospital 7',
		area: 'Area 7',
		gov: 'Gov 7',
		address: 'Address 7',
	},
	{
		id: 8,
		name: 'item 8',
		bloodType: 'AB-',
		volume: 8,
		img: 'image8.jpg',
		hospital: 'Hospital 8',
		area: 'Area 8',
		gov: 'Gov 8',
		address: 'Address 8',
	},
	{
		id: 9,
		name: 'item 9',
		bloodType: 'O+',
		volume: 9,
		img: 'image9.jpg',
		hospital: 'Hospital 9',
		area: 'Area 9',
		gov: 'Gov 9',
		address: 'Address 9',
	},
	{
		id: 10,
		name: 'item 10',
		bloodType: 'A+',
		volume: 10,
		img: 'image10.jpg',
		hospital: 'Hospital 10',
		area: 'Area 10',
		gov: 'Gov 10',
		address: 'Address 10',
	},
	{
		id: 11,
		name: 'item 11',
		bloodType: 'B+',
		volume: 11,
		img: 'image11.jpg',
		hospital: 'Hospital 11',
		area: 'Area 11',
		gov: 'Gov 11',
		address: 'Address 11',
	},
	{
		id: 12,
		name: 'item 12',
		bloodType: 'AB+',
		volume: 12,
		img: 'image12.jpg',
		hospital: 'Hospital 12',
		area: 'Area 12',
		gov: 'Gov 12',
		address: 'Address 12',
	},
	{
		id: 13,
		name: 'item 13',
		bloodType: 'O-',
		volume: 13,
		img: 'image13.jpg',
		hospital: 'Hospital 13',
		area: 'Area 13',
		gov: 'Gov 13',
		address: 'Address 13',
	},
	{
		id: 14,
		name: 'item 14',
		bloodType: 'A-',
		volume: 14,
		img: 'image14.jpg',
		hospital: 'Hospital 14',
		area: 'Area 14',
		gov: 'Gov 14',
		address: 'Address 14',
	},
	{
		id: 15,
		name: 'item 15',
		bloodType: 'B-',
		volume: 15,
		img: 'image15.jpg',
		hospital: 'Hospital 15',
		area: 'Area 15',
		gov: 'Gov 15',
		address: 'Address 15',
	},
	{
		id: 16,
		name: 'item 16',
		bloodType: 'AB-',
		volume: 16,
		img: 'image16.jpg',
		hospital: 'Hospital 16',
		area: 'Area 16',
		gov: 'Gov 16',
		address: 'Address 16',
	},
	{
		id: 17,
		name: 'item 17',
		bloodType: 'O+',
		volume: 17,
		img: 'image17.jpg',
		hospital: 'Hospital 17',
		area: 'Area 17',
		gov: 'Gov 17',
		address: 'Address 17',
	},
	{
		id: 18,
		name: 'item 18',
		bloodType: 'A+',
		volume: 18,
		img: 'image18.jpg',
		hospital: 'Hospital 18',
		area: 'Area 18',
		gov: 'Gov 18',
		address: 'Address 18',
	},
	{
		id: 19,
		name: 'item 19',
		bloodType: 'B+',
		volume: 19,
		img: 'image19.jpg',
		hospital: 'Hospital 19',
		area: 'Area 19',
		gov: 'Gov 19',
		address: 'Address 19',
	},
];

export const teachingPosts: TTeachingPost[] = [
	{
		id: 1,
		name: 'Math Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Math',
		students: 30,
		area: 'Any town',
		gov: 'Any Gov',
	},
	{
		id: 2,
		name: 'Science Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Science',
		students: 40,
		area: 'Other Town',
		gov: 'Other Gov',
	},
	{
		id: 3,
		name: 'English Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'English',
		students: 50,
		area: 'Another Town',
		gov: 'Another Gov',
	},
	{
		id: 4,
		name: 'Art Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Art',
		students: 60,
		area: 'Any town',
		gov: 'Any Gov',
	},
	{
		id: 5,
		name: 'Music Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Music',
		students: 70,
		area: 'Another Town',
		gov: 'Another Gov',
	},
	{
		id: 6,
		name: 'Physical Education Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Physical Education',
		students: 80,
		area: 'Other Town',
		gov: 'Other Gov',
	},
	{
		id: 7,
		name: 'Math Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Math',
		students: 30,
		area: 'Any town',
		gov: 'Any Gov',
	},
	{
		id: 8,
		name: 'Science Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Science',
		students: 40,
		area: 'Other Town',
		gov: 'Other Gov',
	},
	{
		id: 9,
		name: 'English Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'English',
		students: 50,
		area: 'Another Town',
		gov: 'Another Gov',
	},
	{
		id: 10,
		name: 'Art Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Art',
		students: 60,
		area: 'Any town',
		gov: 'Any Gov',
	},
	{
		id: 11,
		name: 'Music Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Music',
		students: 70,
		area: 'Another Town',
		gov: 'Another Gov',
	},
	{
		id: 12,
		name: 'Physical Education Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Physical Education',
		students: 80,
		area: 'Other Town',
		gov: 'Other Gov',
	},
	{
		id: 13,
		name: 'Math Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Math',
		students: 30,
		area: 'Any town',
		gov: 'Any Gov',
	},
	{
		id: 14,
		name: 'Science Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Science',
		students: 40,
		area: 'Other Town',
		gov: 'Other Gov',
	},
	{
		id: 15,
		name: 'English Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'English',
		students: 50,
		area: 'Another Town',
		gov: 'Another Gov',
	},
	{
		id: 16,
		name: 'Art Teacher',
		quantity: 1,
		img: teachingPost,
		subject: 'Art',
		students: 60,
		area: 'Any town',
		gov: 'Any Gov',
	},
];

export const medicalCases: TMedicalCase[] = [
	{
		id: 1,
		name: 'Covid-19',
		quantity: 100,
		img: 'image1.jpg',
		patientName: 'John Doe',
		age: 30,
		gender: 'male',
		weight: 150,
		location: 'Hospital 1',
		street: 'Address 1',
		area: 'Area 1',
		gov: 'Gov 1',
		specialty: 'General',
		description: 'Description 1',
		orgName: 'Org 1',
	},
	{
		id: 2,
		name: 'Covid-19',
		quantity: 200,
		img: '',
		patientName: 'John Doe',
		age: 50,
		gender: 'male',
		weight: 90,
		location: 'Hospital 2',
		street: 'Address 2',
		area: 'Area 2',
		gov: 'Gov 2',
		specialty: 'throat',
		description: 'Description 2',
		orgName: 'Org 2',
	},
	{
		id: 3,
		name: 'Covid-19',
		quantity: 100,
		img: 'image1.jpg',
		patientName: 'John Doe',
		age: 50,
		gender: 'female',
		weight: 300,
		location: 'Hospital 3',
		street: 'Address 3',
		area: 'Area 3',
		gov: 'Gov 3',
		specialty: 'back',
		description: 'Description 3',
		orgName: 'Org 3',
	},
	{
		id: 4,
		name: 'Covid-19',
		quantity: 100,
		img: 'image1.jpg',
		patientName: 'John Doe',
		age: 50,
		gender: 'male',
		weight: 300,
		location: 'Hospital 3',
		street: 'Address 3',
		area: 'Area 3',
		gov: 'Gov 3',
		specialty: 'back',
		description: 'Description 3',
		orgName: 'Org 3',
	},
];

export const toys: TToyItem[] = [
	{
		id: 1,
		name: 'Lego',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: BoardGames,
		gender: 'male',
		category: 'board games',
	},
	{
		id: 2,
		name: 'Barbie',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Dolls,
		gender: 'female',
		category: 'dolls',
	},
	{
		id: 3,
		name: 'Hot Wheels',
		type: 'General',
		ageGroup: 'All',
		quantity: 30,
		img: Cars,
		gender: 'all',
		category: 'cars',
	},
	{
		id: 4,
		name: 'Basketball',
		type: 'General',
		ageGroup: '+9',
		quantity: 10,
		img: Sports,
		category: 'sports',
		gender: 'all',
	},
	{
		id: 5,
		name: 'Soccer Ball',
		type: 'General',
		ageGroup: '+9',
		quantity: 10,
		img: Sports,
		category: 'sports',
		gender: 'all',
	},
	{
		id: 6,
		name: 'Bicycle',
		type: 'General',
		ageGroup: '+12',
		quantity: 10,
		img: Outdoor,
		category: 'Outdoor',
		gender: 'all',
	},
	{
		id: 7,
		name: 'Lego',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: BoardGames,
		category: 'board games',
		gender: 'all',
	},
	{
		id: 8,
		name: 'Barbie',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Dolls,
		category: 'dolls',
		gender: 'female',
	},
	{
		id: 9,
		name: 'Hot Wheels',
		type: 'General',
		ageGroup: 'All',
		quantity: 30,
		img: Cars,
		category: 'cars',
		gender: 'all',
	},
	{
		id: 10,
		name: 'Basketball',
		type: 'General',
		ageGroup: '+9',
		quantity: 10,
		img: Sports,
		category: 'sports',
		gender: 'all',
	},
	{
		id: 11,
		name: 'Soccer Ball',
		type: 'General',
		ageGroup: '+9',
		quantity: 10,
		img: Sports,
		category: 'sports',
		gender: 'all',
	},
	{
		id: 12,
		name: 'Bicycle',
		type: 'General',
		ageGroup: '+12',
		quantity: 10,
		img: Outdoor,
		category: 'Outdoor',
		gender: 'all',
	},
];
export const clothes: TClothesItem[] = [
	{
		id: 1,
		name: 'Jackets',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: Jackets,
		season: 'Winter',
		material: 'Cotton',
		gender: 'all',
	},
	{
		id: 2,
		name: 'Pants',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Pants,
		season: 'Winter',
		material: 'Cotton',
		gender: 'all',
	},
	{
		id: 3,
		name: 'T-Shirts',
		type: 'General',
		ageGroup: '+5',
		quantity: 30,
		img: Shirts,
		season: 'Summer',
		material: 'Cotton',
		gender: 'male',
	},
	{
		id: 4,
		name: 'Jackets',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: Jackets,
		season: 'Winter',
		material: 'Cotton',
		gender: 'all',
	},
	{
		id: 5,
		name: 'Pants',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Pants,
		season: 'Winter',
		material: 'Cotton',
		gender: 'female',
	},
	{
		id: 6,
		name: 'T-Shirts',
		type: 'General',
		ageGroup: '+5',
		quantity: 30,
		img: Shirts,
		season: 'Summer',
		material: 'Cotton',
		gender: 'all',
	},
	{
		id: 7,
		name: 'Jackets',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: Jackets,
		season: 'Winter',
		material: 'Cotton',
		gender: 'male',
	},
	{
		id: 8,
		name: 'Pants',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Pants,
		season: 'Winter',
		material: 'Cotton',
		gender: 'male',
	},
	{
		id: 9,
		name: 'T-Shirts',
		type: 'General',
		ageGroup: '+5',
		quantity: 30,
		img: Shirts,
		season: 'Summer',
		material: 'Cotton',
		gender: 'female',
	},
	{
		id: 10,
		name: 'Jackets',
		type: 'General',
		ageGroup: 'All',
		quantity: 100,
		img: Jackets,
		season: 'Winter',
		material: 'Cotton',
		gender: 'all',
	},
	{
		id: 11,
		name: 'Pants',
		type: 'General',
		ageGroup: '+3',
		quantity: 50,
		img: Pants,
		season: 'Winter',
		material: 'Cotton',
		gender: 'female',
	},
	{
		id: 12,
		name: 'T-Shirts',
		type: 'General',
		ageGroup: '+5',
		quantity: 30,
		img: Shirts,
		season: 'Summer',
		material: 'Cotton',
		gender: 'all',
	},
];
